---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/12/3 14:59
---

local skynet = require "skynet"
local utils = require "utils"
local cjson = require "cjson"
local log = require "log"
local const_game = require "const_game"
local serialize = require "serialize"
require "functions"

cjson.encode_sparse_array(true)

local CMD = {}

skynet.start(function ()
    skynet.dispatch("lua", function (_, _, cmd, ...)
        local f = assert(CMD[cmd])
        skynet.ret(skynet.pack(f(...)))
    end)
end)

function CMD.start(_data)
    local keys = skynet.call(utils.redis_route(), "lua", "keys", table.concat({const_game.REDIS_KEY_SNAPSHOT_ROOM, "*"}))
    log.log("共有房间数[%d]待恢复.", #keys)
    for _, key in pairs(keys) do
        local room_tb = serialize.deseristring_string(skynet.call(utils.redis_route(), "lua", "get", key))
        local room_server = skynet.newservice("room_server", room_tb.m_room_uuid)
        local args = {owner=room_tb.m_room_owner,room_id=tonumber(room_tb.m_room_id),room_uuid=room_tb.m_room_uuid,kwargs=room_tb.m_room_kwargs}
        --dump(room_tb, "room_tb")
        skynet.call(room_server, "lua", "start", args, room_tb)
    end

end