---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/6 14:37
---

local skynet = require "skynet"
local queue = require "skynet.queue"
require "skynet.manager"
require "functions"

local cs = queue()
local rid_to_rsever = {}
local CMD = {}

function CMD.get_room_serve(_room_id)
    return rid_to_rsever[_room_id]
end

function CMD.set_room_serve(_room_id, _room_server)
    rid_to_rsever[_room_id] = _room_server
end

function CMD.remove_room_addr(_room_id)
    rid_to_rsever[_room_id] = nil
end

function CMD.get_all_rooms()
    return rid_to_rsever
end

skynet.start(function ()
    skynet.dispatch("lua", function (_, _, cmd, ...)
        skynet.ret(skynet.pack(CMD[cmd](...)))
    end)

    skynet.register(".room_mgr_server")
end)