---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/2/28 16:43
---

local skynet = require "skynet"
local queue = require "skynet.queue"
local log = require "log"
require "skynet.manager"
require "functions"

local cs = queue()

local aid_to_agent = {}

local CMD = {}

function CMD.set(_aid, _agent)
    local exist = aid_to_agent[_aid]
    if exist then
        log.log("user [%d] agent exist. old[%s], new[%s]", _aid, skynet.address(exist), skynet.address(_agent))
    end
    cs(function ()
        aid_to_agent[_aid] = _agent
    end)
end

function CMD.get(_aid)
    return aid_to_agent[_aid]
end

function CMD.get_all()
    return aid_to_agent
end

function CMD.del(_aid, _agent)
    local agent = aid_to_agent[_aid]
    if agent and agent == _agent then
        aid_to_agent[_aid] = nil
    end
end

skynet.start(function ()
    skynet.dispatch("lua", function (_, _, cmd, ...)
        local f = assert(CMD[cmd])
        skynet.ret(skynet.pack(f(...)))
    end)

    skynet.register(".agent_mgr")
end)