---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/2/12 15:17
---

local skynet = require "skynet"
local socket = require "skynet.socket"

local port = skynet.getenv("httpport")
local agent_size = skynet.getenv("http_snlua_num")

local agent = {}
local CMD = {}

--httpagent服务重启，用于热修复紧急bug
function CMD.restart()
    skynet.error("httpagent restart.")
    local old = {}
    for i, v in pairs(agent) do
        agent[i] = skynet.newservice("http_agent", i)
        old[i] = v
    end
    skynet.timeout(300, function ()
        for _, v in pairs(old) do
            skynet.send(v, "lua", "_exit_")
        end
    end)
    return "Success"
end

skynet.start(function()
    for i= 1, agent_size do
        agent[i] = skynet.newservice("http_agent", i)
    end
    local balance = 1
    skynet.error("Listen web port "..port)
    local id = socket.listen("0.0.0.0", port)
    socket.start(id, function(_id, addr)
        --skynet.error(string.format("%s connected, pass it to agent :%08x", addr, agent[balance]))
        skynet.send(agent[balance], "lua", _id, addr)
        balance = balance + 1
        if balance > #agent then
            balance = 1
        end
    end)

    skynet.dispatch("lua", function (_, _, cmd, ...)
        local f = assert(CMD[cmd])
        skynet.ret(skynet.pack(f(...)))
    end)
end)