---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/7 15:46
---

local skynet = require "skynet"

local webc_server_num = skynet.getenv("webc_snlub_num")

local M = {}
function M._webc_route()
    local route_id = math.random(1, webc_server_num)
    return table.concat({".webclient_", route_id})
end
function M.get(url, get, no_reply, header)
    if no_reply then
        return skynet.send(M._webc_route(), "lua", "request", url, get, nil, no_reply, header)
    else
        return skynet.call(M._webc_route(), "lua", "request", url, get, nil, no_reply, header)
    end
end

function M.post(url, post, no_reply, header)
    if no_reply then
        return skynet.send(M._webc_route(), "lua", "request", url, nil, post, no_reply, header)
    else
        return skynet.call(M._webc_route(), "lua", "request", url, nil, post, no_reply, header)
    end
end

return M