---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2018/12/26 15:45
---

local protobuf = require "pb"
local log = require "log"
local const_proto = require "const_proto"
local const_game = require "const_game"
require "functions"

local pb_files = {
    "../proto/game.pb"
}

local app_id = const_game.APP_ID
local game_id = const_game.GAME_ID
local ver_1 = 1
local ver_2 = 0
local ver_3 = 0

local M = {}

function M.init()
    for _,v in ipairs(pb_files) do
        --log.log("register pb file: %s", v)
        protobuf.loadfile(v)
    end
end

function M.getSize(buff)
    local size = string.unpack(">i4", buff)
    return size
end

function M.getHead(buff)
    local size, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, _, cmd = string.unpack(">i4i4hhi4bbbbbbbbbbbbB", buff)
    return size, cmd
end

function M.pack(_cmd, _data, _msgid)
    local p_name = assert(const_proto[_cmd], string.format("protopack pack error cmd [%s] undefined!", _cmd))
    local data = protobuf.encode(table.concat({p_name, "Response"}), _data)
    local len = #data
    local pack = string.pack(">i4i4hhi4bbbBc"..len, len + 20, _msgid, app_id, game_id, os.time(), ver_1, ver_2, ver_3, _cmd, data)
    return pack
end

function M.unpack(buff)
    local size, cmd = M.getHead(buff)
    local body = string.unpack(">c"..(size - 29), buff, 30)
    local p_name = assert(const_proto[cmd], string.format("protopack unpack error cmd [%d] undefined!", cmd))
    local msg = protobuf.decode(table.concat({p_name, "Request"}), body)
    return cmd, msg
end

--初始化注册pb文件
M.init()

return M