---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/4 11:47
---

local const_cmd = require "const_cmd"
local game_ctl = require "game_ctl"

return {
    --_c 控制器; _m 方法名; _p 协议号(可选，默认为调用协议号)
    [const_cmd.HEART_BEAT]                = {_c=game_ctl, _m="heart_beat"},
    [const_cmd.ENTER_ROOM]                = {_c=game_ctl, _m="enter_room"},
    [const_cmd.EXIT_ROOM]                 = {_c=game_ctl, _m="exit_room"},
    [const_cmd.DISMISS_ROOM]              = {_c=game_ctl, _m="dismiss_room"},
    [const_cmd.READY]                     = {_c=game_ctl, _m="ready"},
    [const_cmd.LORD]                      = {_c=game_ctl, _m="rob"},
    [const_cmd.CHANGE]                    = {_c=game_ctl, _m="bury"},
    [const_cmd.REBEL]                     = {_c=game_ctl, _m="rebel"},
    [const_cmd.DISCARD]                   = {_c=game_ctl, _m="discard"},
    [const_cmd.PLAYER_VOTE]               = {_c=game_ctl, _m="player_vote"},
    [const_cmd.SPEAKER]                   = {_c=game_ctl, _m="speaker"},
    [const_cmd.ROBOT]                     = {_c=game_ctl, _m="robot"},
    [const_cmd.SURRENDER]                 = {_c=game_ctl, _m="surrender"},
    [const_cmd.CHECK_BURY_CARD]           = {_c=game_ctl, _m="check_bury_card"},
    [const_cmd.CHECK_SCORE_CARD]          = {_c=game_ctl, _m="check_score_card"},
    [const_cmd.CHECK_PREV_CARD]           = {_c=game_ctl, _m="check_prev_card"},
}