---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/4 9:28
---

local M = {
    SUCESS                      = 1,
    FAILURE                     = 1000,
    ROOM_NOT_EXIST              = 5001,   --房间不存在
    ROOM_IP_WARNING             = 5010,   --IP预警
    ROOM_GPS_WARNING            = 5011,   --GPS预警
    ROOM_IS_FULL                = 5002,   --房间已满
    ROOM_DISMISS_FAILURE        = 7040,   --房间解散房间失败

    --房间解散代码
    DISMISS_ROOM_CODE = {
        VOTE                  = 2, --投票解散
        NORMAL                = 3, --正常解散
        OWNER                 = 4, --房主提前解散
        ADMIN                 = 5, --管理员强制解散
        TIMEOUT               = 6, --超时自动解散
        SCORE_LESS            = 7, --积分不足解散
        ROBOT                 = 8, --托管状态下局自动解散
    }
}

return M