---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/2 15:52
---

local M = {
    ["/customize_cards"]                               = {_c="http_api_ctl", _m="customize_cards"},

    ["/web/create_room"]                               = {_c="http_api_ctl", _m="create_room"},
    ["/web/room_check"]                                = {_c="http_api_ctl", _m="room_check"},
    ["/web/dismiss"]                                   = {_c="http_api_ctl", _m="web_dismiss"},

    ["/web/table_status"]                              = {_c="http_api_ctl", _m="table_status"},
    ["/query_rooms"]                                   = {_c="http_api_ctl", _m="query_rooms"},
    ["/clear_room"]                                    = {_c="http_api_ctl", _m="clear_room"},
    ["/test"]                                          = {_c="http_api_ctl", _m="test"},
}

return M