---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/4 9:33
---

local const_cmd = require "const_cmd"
return {
    [const_cmd.ENTER_ROOM]                    = "xsdq.EnterRoom",
    [const_cmd.ENTER_ROOM_OTHER]              = "xsdq.EnterRoomOther",
    [const_cmd.EXIT_ROOM]                     = "xsdq.ExitRoom",
    [const_cmd.DISMISS_ROOM]                  = "xsdq.DismissRoom",
    [const_cmd.SPONSOR_VOTE]                  = "xsdq.SponsorVote",
    [const_cmd.PLAYER_VOTE]                   = "xsdq.PlayerVote",
    [const_cmd.ONLINE_STATUS]                 = "xsdq.OnlineStatus",
    [const_cmd.SPEAKER]                       = "xsdq.Speaker",
    [const_cmd.READY]                         = "xsdq.Ready",
    [const_cmd.HEART_BEAT]                    = "xsdq.Heartbeat",
    [const_cmd.SETTLE_FOR_ROUND]              = "xsdq.SettleForRound",
    [const_cmd.SETTLE_FOR_ROOM]               = "xsdq.SettleForRoom",
    [const_cmd.RECONNECT]                     = "xsdq.Reconnect",
    [const_cmd.ROBOT]                         = "xsdq.Robot",
    [const_cmd.PUSH_MESSAGE]                  = "xsdq.PushMessage",
    [const_cmd.DEAL]                          = "xsdq.Deal",
    [const_cmd.DRAW]                          = "xsdq.Draw",
    [const_cmd.DISCARD]                       = "xsdq.Discard",
    [const_cmd.SYNCHRONISE_CARDS]             = "xsdq.SynchroniseCards",
    [const_cmd.DISCARD_TIPS]                  = "xsdq.DiscardTips",
    [const_cmd.LORD_NOTICE]                   = "xsdq.LordNotice",
    [const_cmd.LORD]                          = "xsdq.Lord",
    [const_cmd.CATCH_BOTTOM]                  = "xsdq.BCNotice",
    [const_cmd.CHANGE]                        = "xsdq.ChangeBottom",
    [const_cmd.REBEL_NOTICE]                  = "xsdq.RebelNotice",
    [const_cmd.REBEL]                         = "xsdq.Rebel",
    [const_cmd.POINT_CHANGE]                  = "xsdq.PointChange",
    [const_cmd.PICKUP_POINT]                  = "xsdq.PickupPoint",
    [const_cmd.MINGJI]                        = "xsdq.Mingji",
    [const_cmd.SURRENDER]                     = "xsdq.Surrender",
    [const_cmd.SHOW_LORD_CARD]                = "xsdq.ShowLordCard",
    [const_cmd.STEP_START]                    = "xsdq.StepStart",
    [const_cmd.CHECK_BURY_CARD]               = "xsdq.CheckBuryCards",
    [const_cmd.CHECK_SCORE_CARD]              = "xsdq.CheckScoreCards",
    [const_cmd.CHECK_PREV_CARD]               = "xsdq.CheckPrevCards",
}