---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by b_ree.
--- DateTime: 2019/11/4 9:32
---

return {
    ENTER_ROOM                     = 2,          -- 进入房间
    ENTER_ROOM_OTHER               = 3,          -- 其他人进入房间
    EXIT_ROOM                      = 5,          -- 离开房间
    DISMISS_ROOM                   = 7,          -- 解散房间
    SPONSOR_VOTE                   = 11,         -- 发起投票
    PLAYER_VOTE                    = 12,         -- 玩家投票
    ONLINE_STATUS                  = 13,         -- 玩家在线状态广播
    SPEAKER                        = 14,         -- 大喇叭
    READY                          = 15,         -- 准备
    HEART_BEAT                     = 16,         -- 心跳
    SETTLE_FOR_ROUND               = 17,         -- 小结算
    SETTLE_FOR_ROOM                = 18,         -- 大结算
    RECONNECT                      = 19,         -- 重连
    ROBOT                          = 20,         -- 托管
    PUSH_MESSAGE                   = 21,         -- 推送消息
    DEAL                           = 22,         -- 起手发牌
    DRAW                           = 23,         -- 摸牌
    DISCARD                        = 24,         -- 出牌
    SYNCHRONISE_CARDS              = 25,         -- 服务端主动同步手牌
    DISCARD_TIPS                   = 26,         -- 出牌提示
    LORD_NOTICE                    = 27,         -- 通知叫主
    LORD                           = 28,         -- 叫主
    CATCH_BOTTOM                   = 29,         -- 拿底
    CHANGE                         = 30,         -- 埋底
    REBEL_NOTICE                   = 31,         -- 通知反主
    REBEL                          = 32,         -- 反主
    POINT_CHANGE                   = 33,         -- 桌面分数广播
    PICKUP_POINT                   = 34,         -- 玩家捡分广播
    MINGJI                         = 35,         -- 明鸡广播
    SURRENDER                      = 36,         -- 认输
    SHOW_LORD_CARD                 = 37,         -- 显示朋友牌，主花色
    STEP_START                     = 38,         -- 进入出牌广播
    CHECK_BURY_CARD                = 39,         -- 查看埋底牌
    CHECK_SCORE_CARD               = 40,         -- 查看捡分牌
    CHECK_PREV_CARD                = 41,         -- 查看上轮牌
}